use_frameworks!

platform :ios, '9.3'

target 'Markdown_Example' do
  pod 'Markdown', :path => '../'

  target 'Markdown_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
